---
title: "Index Vectors Solutions"
output: html_notebook
---
#Solution to exercise 1
```{r}
x <- c("ww", "ee", "ff", "uu", "kk")
x[c(2,3)]
```
#Solution to exercise 2
```{r}
x <- c("ss", "aa", "ff", "kk", "bb")
x[c(2, 4, 4)]
#"kk"
```
#Solution to exercise 3
```{r}
x <- c("pp", "aa", "gg", "kk", "bb")
x[-2]
#"kk", which was wrong.  The -2 removes the second piece.  
```
#Solution to exercise 4
```{r}
a <- c(2, 4, 6, 8) 
b <- c(TRUE, FALSE, TRUE, FALSE)
max(a[b])
#6
```
#Solution to exercise 5
```{r}
a <- c(2, 4, 6, 8) 
b <- c(TRUE, FALSE, TRUE, FALSE)
sum(a[b])
#8
```
#Solution to exercise 6
```{r}
x <- c(2, 1, 4, 2, 1, NA)
sum(x[1:length(x)-1])
```
#Solution to exercise 7
```{r}
x <- c(1, 3, 5, 7, NA)
x[1:length(x)-1]
#1, 3, 5, 7
```
#Solution to exercise 8
```{r}
s <- data.frame(first= as.factor(c("x", "y", "a", "b", "x", "z")), second=c(2, 4, 6, 8, 10, 12))
names(s)
s$second[s$first=='x' | (s$first == 'y')]
#I did not get this one.  I don't think I ever would get this without googling or looking at stack overflow
s$second[s$first %in% c('x', 'y')]
```
#Solution to exercise 9
```{r}
(c(FALSE, TRUE)) || (c(TRUE, TRUE))
#True
```
#Solution to exercise 10
```{r}
x <- c(1, 3, 6, 7, 3, 7, 8, 9, 3, 7, 2)
#my solution: x[x == 3 | x == 7] which would just return the x's that have the value of 3 and 7
which(x %in% c(3,7))
#the solution here uses the which function and %in% command to search for the 3's and 7's in x and return their position
```


